name: school_program
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  intl: ^0.17.0
  share_plus: ^6.3.0
  dynamic_color: ^1.4.0
  icons_launcher: ^2.0.4
  flutter_native_splash: ^2.2.9
  animations: ^2.0.7
  get: 4.6.5
  flutter: 
    sdk: flutter
  get_storage: ^2.1.1
  uuid: ^3.0.7
  flutter_animate: ^4.1.0
  awesome_notifications: ^0.7.4+1
  reorderables: ^0.6.0

dev_dependencies: 
  flutter_launcher_icons_maker: ^0.10.2
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

flutter_icons: 
  image_path: assets/icons/school.png
  adaptive_icon_background: '#FFFFFF'
  android: true
  ios: true

